name: Testing tag

on:
  push:
    branches:
      - crazy-experiment

jobs:
  tag_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and tag test
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}